### ISSUE TITLE
I'm building a flutter app that saves card info

### ISSUE THREAD

**Issue by Raviteja11122** [iamvivekkaushik/AwesomeCard#1]
@iamvivekkaushik 
India cards have additional security like some random data at the backside like the below picture. I want to store this information

![ncashcard](https://user-images.githubusercontent.com/49988053/71476367-b59d7280-280a-11ea-85c5-fc2e8d886222.gif)

**Comment by iamvivekkaushik** [comment]
Hi @Raviteja11122, I am not planning to add the grid like structure on the back of the card. However I will make it so that you can create your own layout and use that.
