### ISSUE TITLE
Right overflowed by 4.0 pixels

### ISSUE THREAD

**Issue by Mohammadhamza43** [iamvivekkaushik/AwesomeCard#10]
![screenshot-1587505000838](https://user-images.githubusercontent.com/26992726/79916432-27489e80-8442-11ea-820e-3c9841297dac.jpg)
getting this error how to resolve this.
Here is the code
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.indigo,
        title: Text("Saved Cards"),
      ),
      body: Builder(builder: (BuildContext context) {
        return Column(
//          mainAxisAlignment: MainAxisAlignment.end,
          children: <Widget>[
            CreditCard(
              cardNumber: "5450 7879 4864 7854",
              cardExpiry: "10/25",
              cardHolderName: "Mohammad Hamza Gaya",
              cvv: "456",
              bankName: "Axis Bank",
              showBackSide: false,
              frontBackground: CardBackgrounds.black,
              backBackground: CardBackgrounds.black,
              showShadow: false,
            ),
            Padding(
              padding: const EdgeInsets.all(8.0),
              child: Container(
                  color: Colors.indigo,
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: <Widget>[
                      Expanded(
                        child: FlatButton(
                            onPressed: () {
                              Navigator.pushNamed(context, '/addNewCard');
                            },
                            child: Text(
                              "Add New Card",
                              style:
                              TextStyle(fontSize: 18, color: Colors.white),
                            )),
                      ),
                    ],
                  )),
            ),
          ],
        );
      }),
    );

**Comment by iamvivekkaushik** [comment]
Thanks, for this. I'll take a look at it.

**Comment by Dharaneshvar** [comment]
Is the issue resolved? I'm too facing the same issue

**Comment by NKoroloff** [comment]
I'm too facing the same issue

**Comment by jacopofranza** [comment]
+1

**Comment by iamvivekkaushik** [comment]
This is fixed in the latest version.
