### ISSUE TITLE
CVV Render overflowed 40 px

### ISSUE THREAD

**Issue by malopezr7** [iamvivekkaushik/AwesomeCard#13]
to solve this just edit the file card_back_layout.dart and modify the return with this.

    return Column(
      mainAxisAlignment: MainAxisAlignment.start,
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        SizedBox(
          height: 30,
        ),
        Expanded(
          child: Container(
            color: Colors.black,
            height: 50,
          ),
        ),
        SizedBox(
          height: 20,
        ),
        Row(
          mainAxisAlignment: MainAxisAlignment.start,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            Expanded(
              child: Container(
                color: Colors.grey,
                height: 50,
              ),
              flex: 3,
            ),
            Expanded(
                flex: 1,
                child: Center(
                  child: Text(
                    cvv.toString(),
                    style: TextStyle(
                        fontSize: 21,
                        fontWeight: FontWeight.w500,
                        color: Colors.black
                    ),
                  ),
                )
            ),
          ],
        ),

        SizedBox(
          height: 40,
        ),
      ],
    );
it is responsive, please apply y the next update.

regards

**Comment by iamvivekkaushik** [comment]
Hi @malopezr7, thanks for pointing it out. I'll update it in the next version.

**Comment by marianoarga** [comment]
friendly ping

**Comment by razerduy** [comment]
friendly ping

**Comment by iamvivekkaushik** [comment]
So, sorry guys. I have ton of work on hand that I need to finish. Will try to fix it this week.
