### ISSUE TITLE
Does not work on flutter web

### ISSUE THREAD

**Issue by lleewwiiss** [iamvivekkaushik/AwesomeCard#14]
Running the example app on flutter web shows that the animation is broken, the card does rotate but there is that constant artifact in the middle.

![Screenshot from 2020-05-21 16-19-30](https://user-images.githubusercontent.com/7379418/82529671-e3e76a00-9b7e-11ea-8d46-dc211b18d856.png)

**Comment by iamvivekkaushik** [comment]
I haven't tried on flutter web, it works fine on the mobile apps.

**Comment by ortal83cohen** [comment]
I have the same issue on web.

**Comment by MaNoOoz** [comment]
guyz anyone knows how to solve this 
`Target debug_android_application failed: FileSystemException: Cannot copy file to '... \build\app\intermediates\flutter\debug\flutter_assets\packages/awesome_card/images/card_provider/american_express.png', path = 'H:\FlutterSDK\.pub-cache\hosted\pub.dartlang.org\awesome_card-1.1.0\images\card_provider\american_express.png' (OS Error: The system cannot find the path specified.
, errno = 3)
build failed.`

**Comment by gorillatapstudio** [comment]
I found the same issue on web

**Comment by diegogarciar** [comment]
Hello, I just tested this on flutter 2.5.3 and I couldn't reproduce the issue, Are you still experiencing it?
