### ISSUE TITLE
null-safety 

### ISSUE THREAD

**Issue by Cyphontin** [iamvivekkaushik/AwesomeCard#22]
Do you plan to update to null-safety ?
Thank you

howing dependencies that are currently not opted in to null-safety.
[✗] indicates versions without null safety support.
[✓] indicates versions opting in to null safety.

Package Name  Current  Upgradable  Resolvable  Latest  

direct dependencies:
awesome_card  ✗1.1.0   ✗1.1.0      ✗1.1.0      ✗1.1.0  
You are already using the newest resolvable versions listed in the 'Resolvable' column.
Newer versions, listed in 'Latest', may not be mutually compatible.

**Comment by diegogarciar** [comment]
Closing this as this package is currently in null safety
