### ISSUE TITLE
Default horizontal margin

### ISSUE THREAD

**Issue by Fyrok1** [iamvivekkaushik/AwesomeCard#25]
it's a deal breaker for style.
please remove default horizontal margin.
![image](https://user-images.githubusercontent.com/31103042/118282914-7642f500-b4d7-11eb-92fd-c343436f76b9.png)

**Comment by Fyrok1** [comment]
pull requst : https://github.com/iamvivekkaushik/AwesomeCard/pull/26

**Comment by diegogarciar** [comment]
Closing this with #24 fix, Thank you anyways for submitting the PR!
