### ISSUE TITLE
Manually add card brand

### ISSUE THREAD

**Issue by assad62** [iamvivekkaushik/AwesomeCard#3]
Hi,

First of all thank you for the widget. In my use case I am using stripe to store the card info, so on the front end stripe will only return the last 4 digits of the card, so by that method I cannot get card brand to show in this widget.

However stripe, returns the card brand (i.e. Visa, Master Card etc). So would be great if you can add a field in your card initialiser that allows us to manually add a card brand.

Thanks!

**Comment by iamvivekkaushik** [comment]
Sure thing, I will add this today. Thanks for using the lib.

**Comment by vinnytwice** [comment]
@assad62 hi sorry for the OT, what package are you using to implement Stripe?

**Comment by assad62** [comment]
Hi @vinnytwice , when i made this post i was using : https://pub.dev/packages/stripe_payment

But looks it's discontinued now, but perhaps this might help: https://pub.dev/packages/flutter_stripe
