### ISSUE TITLE
BackgroundCard Color

### ISSUE THREAD

**Issue by FreakCarlos** [iamvivekkaushik/AwesomeCard#5]
Is there any way that we can change the BackgroundCard Color?
For example red or blue so we can make it approach to the user's card.

Thank You

**Comment by iamvivekkaushik** [comment]
Oh yeah, totally. Just check the constructor [here](https://github.com/iamvivekkaushik/AwesomeCard#-usage).

You just need to pass the color to the `frontBackground` and `backBackground` argument depending on which side color you are trying to change.

**Comment by FreakCarlos** [comment]
but when I tried and the unique colors available are white and black

**Comment by FreakCarlos** [comment]
Okay, I could made it by adding a Container(color: Colors.whateverColor) on the  `frontBackground` or the  `backBackground`

**Comment by iamvivekkaushik** [comment]
Yeah, just pass this as your `frontBackground` or the `backBackground` argument.

```dart
 Container(
    width: double.maxFinite,
    height: double.maxFinite,
    color: Colors.whateverColor,
  );
```
