### ISSUE TITLE
Too much size for the form

### ISSUE THREAD

**Issue by fvisticot** [iamvivekkaushik/AwesomeCard#6]
Displaying the card, the form with 4 lines and the keyboard takes too much place on a normal screen.
Do you plan to provide a more compact layout of the form on 1 on 2 lines maximum ?
1 line form layout:  https://stripe.com/docs/stripe-js

**Comment by iamvivekkaushik** [comment]
This library only provides the card and not the form. You can create the form anyways you like, it is only added to example for demo purpose.
