### ISSUE TITLE
Get card type

### ISSUE THREAD

**Issue by marianoarga** [iamvivekkaushik/AwesomeCard#7]
Hello, how I get the card type once the user has finished the number?

**Comment by iamvivekkaushik** [comment]
It automatically detects the card type you don't need to provide it as a parameter.

**Comment by marianoarga** [comment]
@iamvivekkaushik I mean, how do I listen for a detection, since I want to use that type on the future

**Comment by iamvivekkaushik** [comment]
This library does not provide that functionality. However you can copy the code from`lib/extra/helper.dart` and use it in your app.

**Comment by iamvivekkaushik** [comment]
I'm closing this issue since it is not related to this package.
