### ISSUE TITLE
amex mask

### ISSUE THREAD

**Issue by sante85** [iamvivekkaushik/AwesomeCard#9]
amex mask is not right
xxxx xxxxx xxx

**Comment by iamvivekkaushik** [comment]
I'm not using any mask. Can you clarify your issue?

**Comment by sante85** [comment]
If I write an amex card awesome card show xxxx xxxx xxxx xxxx instead of xxxx xxxxxx xxxxx such as
amex standard
https://lh3.googleusercontent.com/proxy/hhnH--91FJzs4PShUVyMDK5hGrB3uZHyyEQcOAzslbUM-1z3czs3JuDwLyaOrvginq1ZNb_HcSAkFSVTB9NU-NexhaHiKG5QdfZ-EThISuHTLQPAOkZosoAbXhl_GrDijssD3ZY-uCPNSbEN

**Comment by iamvivekkaushik** [comment]
Ohh, got it. I'll fix that in the next update.

**Comment by sante85** [comment]
thank you.

Best regards


Il giorno mer 22 apr 2020 alle ore 20:04 Vivek Kaushik <
notifications@github.com> ha scritto:

**Comment by sante85** [comment]
can notify me when execute this update?

**Comment by iamvivekkaushik** [comment]
I don't have an exact date to give you, but I'll update you here once it is done.

**Comment by diegog-sf** [comment]
Hello, this has been resolved here https://github.com/iamvivekkaushik/AwesomeCard/commit/29aaf78e24aeb760b9fc9a29efdcc6a3756989d8
